repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: pretty-format-json
    args: [--autofix]
  - id: check-yaml
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: end-of-file-fixer
  - id: trailing-whitespace
