" set nocompatible
" filetype off
"
" set rtp+=~/.vim/bundle/Vundle.vim
" call vundle#begin()
" Plugin 'VundleVim/Vundle.vim'
" Plugin 'joshdick/onedark.vim'
" Plugin 'itchyny/lightline.vim'
" Plugin 'vim-airline/vim-airline'
" Plugin 'vim-airline/vim-airline-themes'
" Plugin 'scrooloose/nerdtree'
" call vundle#end()
" filetype plugin indent on
call plug#begin('~/.vim/plugged')
Plug 'joshdick/onedark.vim'
" Plug 'itchyny/lightline.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
call plug#end()

set autoindent
set cindent

set nu

set ts=4
set shiftwidth=4

set mouse=a " mouse cursor integration
set laststatus=2

set backspace=indent,eol,start

"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

syntax on

" let g:airline_statusline_ontop=1 " status line on top
" set statusline=\ %<%l:%v\ [%P]%=%a\ %h%m%r\ %F\
let g:airline#extensions#tabline#enabled=1
autocmd vimenter * NERDTree " Start NerdTree on vim open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Toggle File Tree
map <C-\> :NERDTreeToggle<CR>
" Vertical Split. Simulates New tab
map <C-t> :vsp

let g:airline_theme='onedark'
colorscheme onedark
