tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Personal
brew "mas"

cask "alfred"
# cask "airfoil"
# cask "airserver"
cask "bartender"
cask "bettertouchtool"
cask "movist-pro"
cask "steam"
cask "typora"
# cask "virtualbox"
# cask "vlc"
cask "quitter"

mas "Amphetamine", id: 937984704
mas "Between", id: 1320741520
mas "Fantastical", id: 975937182
mas "isHUD", id: 484757536
mas "KakaoTalk", id: 869223134
mas "Microsoft To Do", id: 1274495053
mas "Monit", id: 1014850245
mas "Monosnap", id: 540348655
mas "Paste - Clipboard Manager", id: 967805235
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "The Unarchiver", id: 425424353

# Development
brew "go"
brew "openssl"
brew "peco"
brew "python"

cask "atom"
cask "dash"
cask "docker"
cask "github"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "jetbrains-toolbox"
cask "sequel-pro"

mas "LittleIpsum", id: 405772121
mas "2Icon", id: 1049625579

# Fonts
tap "homebrew/cask-fonts"
cask "font-monoid"
cask "font-noto-sans"
cask "font-noto-sans-cjk"
