# Brewfile
# Some large apps such as Final Cut Pro X is omitted.

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-versions"

# Personal
brew "mas"

cask "aerial" # Screen Saver.
cask "alfred"
# cask "airfoil"
# cask "airserver"
cask "bartender"
cask "bettertouchtool"
# cask "cheatsheet"
# cask "ckan"
cask "discord"
cask "minecraft"
# cask "mono-mdk" # ckan dependency
cask "hazeover"
cask "mendeley"
cask "movist-pro"
cask "oracle-jdk" # minecraft forge dependancy
cask "steam"
cask "typora"
# cask "rectangle"
# cask "rocket"
# cask "virtualbox"
# cask "vlc"
cask "quitter"

mas "Amphetamine", id: 937984704
# mas "Between", id: 1320741520
mas "Fantastical", id: 975937182
mas "isHUD", id: 484757536
mas "KakaoTalk", id: 869223134
mas "Microsoft To Do", id: 1274495053
mas "Monit", id: 1014850245
# mas "Paste - Clipboard Manager", id: 967805235
mas "Slack", id: 803453959
# mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "The Unarchiver", id: 425424353

# Development
# tap "homebrew/command-not-found"

brew "bat"
brew "cocoapods"
brew "direnv"
# brew "docker"
brew "exa"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "go"
brew "gpg"
brew "jq"
brew "openssl"
brew "peco"
brew "pstree"
brew "python"
brew "rust"
brew "swiftlint"
brew "thefuck"
brew "tig"
brew "tmux"
brew "vim"
brew "zsh"
brew "zplug"

cask "cocoapods"
# cask "dash"
cask "docker"
cask "github"
cask "gitkraken"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "insomnia"
cask "iterm2"
# cask "java6"
cask "jetbrains-toolbox"
# cask "logisim"
cask "notion"
cask "sequel-pro"
# cask "sourcetree"
# cask "vagrant"
cask "visual-studio-code"
# cask "wireshark"
# cask "zoomus"

# mas "2Icon", id: 1049625579
mas "Octotree Pro", id: 1457450145

# Fonts
tap "homebrew/cask-fonts"
cask "font-monoid"
cask "font-fira-code"
cask "font-nanum-gothic"
cask "font-noto-sans"
cask "font-noto-sans-cjk"
cask "font-linux-libertine"

tap "gerrit/homebrew-fonts-sanfrancisco"
cask "font-sanfrancisco"

