name: setup

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  setup:
    strategy:
      matrix:
        os:
        - macos-14
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: ./setup.sh
      env:
        SETUP_ROOT: ${{ github.workspace }}
